### ISSUE TITLE
Improve Efficiency of website

### ISSUE THREAD

**Issue by ShubhankarKG** [DSC-VJTI/CA-Website#80]
The [Pagespeed Insights' result](https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fwww.prideca.in%2F) shows that there are certain optimizations that we can do.

This is a tracking issue to optimizations:
1. Client side route based code splitting using `React.lazy()`.
2. Serving all images in `.webp` format (either manually or through an image store like cloudinary).

Will add more as and when needed.

**Comment by thedarkdivinity** [comment]
Shubhankar,from the dsc vjti website which was built we noticed that webp images were not visible on some IOS devices like iphone6 and my Ipad 4. However,we can surely lazy load these images .
